-- MySQL Script generated by MySQL Workbench
-- Fri Aug 18 13:59:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bikedoctor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bikedoctor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bikedoctor` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bikedoctor` ;

-- -----------------------------------------------------
-- Table `bikedoctor`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`areas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `city_id_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `city_id`
    FOREIGN KEY (`city_id`)
    REFERENCES `bikedoctor`.`cities` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`makes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`makes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`bikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`bikes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `make_id` INT NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `make_id_idx` (`make_id` ASC) VISIBLE,
  CONSTRAINT `make_id`
    FOREIGN KEY (`make_id`)
    REFERENCES `bikedoctor`.`makes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`security_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`security_questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `security_ques_id` INT NOT NULL,
  `answer` VARCHAR(45) NOT NULL,
  `user_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sec_ques_id_idx` (`security_ques_id` ASC) VISIBLE,
  INDEX `user_type_id_idx` (`user_type_id` ASC) VISIBLE,
  CONSTRAINT `sec_ques_id`
    FOREIGN KEY (`security_ques_id`)
    REFERENCES `bikedoctor`.`security_questions` (`id`),
  CONSTRAINT `user_type_id`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `bikedoctor`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `area_id` INT NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `login_id_idx` (`login_id` ASC) VISIBLE,
  INDEX `area_id_idx` (`area_id` ASC) VISIBLE,
  CONSTRAINT `area_cust_id`
    FOREIGN KEY (`area_id`)
    REFERENCES `bikedoctor`.`areas` (`id`),
  CONSTRAINT `login_id`
    FOREIGN KEY (`login_id`)
    REFERENCES `bikedoctor`.`login` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`packages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `details` VARCHAR(200) NOT NULL,
  `cost` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`service_centre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`service_centre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `area_id` INT NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `login_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `login_id_idx` (`login_id` ASC) VISIBLE,
  INDEX `area_sc_id_idx` (`area_id` ASC) VISIBLE,
  CONSTRAINT `area_sc_id`
    FOREIGN KEY (`area_id`)
    REFERENCES `bikedoctor`.`areas` (`id`),
  CONSTRAINT `login_sc_id`
    FOREIGN KEY (`login_id`)
    REFERENCES `bikedoctor`.`login` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`statuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `booking_date` DATETIME NOT NULL,
  `appointment_date` DATETIME NULL DEFAULT NULL,
  `package_id` INT NOT NULL,
  `ser_cen_id` INT NOT NULL,
  `bike_id` INT NOT NULL,
  `bike_reg_no` VARCHAR(45) NOT NULL,
  `base_price` INT NOT NULL,
  `extra_price` INT NOT NULL,
  `estimated_price` INT NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `appointment_date_UNIQUE` (`appointment_date` ASC) VISIBLE,
  INDEX `cust_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `package_id_idx` (`package_id` ASC) VISIBLE,
  INDEX `serv_cent_id_idx` (`ser_cen_id` ASC) VISIBLE,
  INDEX `bike_id_idx` (`bike_id` ASC) VISIBLE,
  INDEX `status_id_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `bike_id`
    FOREIGN KEY (`bike_id`)
    REFERENCES `bikedoctor`.`bikes` (`id`),
  CONSTRAINT `cust_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bikedoctor`.`customers` (`id`),
  CONSTRAINT `package_id`
    FOREIGN KEY (`package_id`)
    REFERENCES `bikedoctor`.`packages` (`id`),
  CONSTRAINT `serv_cent_id`
    FOREIGN KEY (`ser_cen_id`)
    REFERENCES `bikedoctor`.`service_centre` (`id`),
  CONSTRAINT `status_id`
    FOREIGN KEY (`status`)
    REFERENCES `bikedoctor`.`statuses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`payment_modes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`payment_modes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_mode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NOT NULL,
  `comment` VARCHAR(256) NULL DEFAULT NULL,
  `customer_id` INT NOT NULL,
  `serv_cen_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `ser_centre_id_idx` (`serv_cen_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bikedoctor`.`customers` (`id`),
  CONSTRAINT `ser_centre_id`
    FOREIGN KEY (`serv_cen_id`)
    REFERENCES `bikedoctor`.`service_centre` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bikedoctor`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikedoctor`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `payment_mode_id` INT NOT NULL,
  `transaction_number` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `payment_id_idx` (`payment_mode_id` ASC) VISIBLE,
  INDEX `payment_mode_id_idx` (`payment_mode_id` ASC) VISIBLE,
  INDEX `cstmr_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `cstmr_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bikedoctor`.`customers` (`id`),
  CONSTRAINT `payment_mode_id`
    FOREIGN KEY (`payment_mode_id`)
    REFERENCES `bikedoctor`.`payment_modes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
